# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
